//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace journey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRIVER
    {
        public int ID { get; set; }
        public string EMAIL { get; set; }
        public string LOCFROM { get; set; }
        public string LOCTO { get; set; }
        public string DEPARTDATE { get; set; }
        public string DEPARTTIME { get; set; }
        public string DateKeyIn { get; set; }
    }
}
