//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace journey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POI
    {
        public int ID { get; set; }
        public string RSA_Name { get; set; }
        public string RSA_Type { get; set; }
        public Nullable<int> Country_Code { get; set; }
        public string RSA_Status { get; set; }
        public Nullable<int> Cluster_Code { get; set; }
    }
}
