//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace journey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POI2
    {
        public int ID { get; set; }
        public Nullable<int> GROUP_ID { get; set; }
        public string PLACE_NAME { get; set; }
        public string PLACE_CAT { get; set; }
        public string PLACE_STATE { get; set; }
        public string image_url { get; set; }
    }
}
